version: 2.1

defaults:
  - &attach_workspace
      attach_workspace:
        at: /tmp/build_space/
  - &docker_login
      run: docker login -u abbuilder -p "$DOCKER_PASSWORD"
  - &job
      docker:
        - image: circleci/node:10
      working_directory: /tmp/build_space/git_repo
  - &workflow
      context: org-global
  - &workflow-master-only
      context: org-global
      filters:
        branches:
          only:
            - master

jobs:
  pre-build:
    docker:
      - image: circleci/node:12
    steps:
      - run: mkdir build_space
      - add_ssh_keys
      - checkout:
          path: /tmp/build_space/git_repo
      - persist_to_workspace:
          root: /tmp/build_space
          paths:
            - git_repo

  react:
    <<: *job
    steps:
      - *attach_workspace
      - restore_cache:
          keys:
            - v1-react-{{ checksum "react/package.json" }}
      - run:
          name: install dependencies
          command: |-
            cd react
            echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > .npmrc && npm i
      - run:
          name: lint
          command: |-
            cd react
            npm run lint
      - run:
          name: Test
          command: |-
            cd react
            npm run test:ci
      - save_cache:
          key: v1-react-{{ checksum "react/package.json" }}
          paths:
            - react/node_modules

  e2e:
    <<: *job
    steps:
      - *attach_workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - *docker_login
      - run:
          name: build
          command: |-
            docker-compose -f docker-compose.yml -f react/e2e/compose-integration.yml build --build-arg NPM_TOKEN=$PRIVATE_NPM_TOKEN api react e2e
      - run:
          name: start the test stack
          command: |-
            docker-compose  -f docker-compose.yml -f react/e2e/compose-integration.yml up -d api react discovery e2e
      - run:
          name: Run the puppeteer tests
          command: docker-compose -f docker-compose.yml -f react/e2e/compose-integration.yml exec e2e npm run test:ci

  api:
    <<: *job
    steps:
      - *attach_workspace
      - run:
          name: install dependencies
          command: |-
            cd api && echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > .npmrc && npm i
      - run:
          name: lint
          command: |-
            cd api
            npm run lint
      - run:
          name: unit test api
          command: |-
            cd api
            npm run test:ci
      - run:
          name: integration test api
          command: |-
            cd api
            npm run test:integration:ci
      - save_cache:
          key: v1-api-{{ checksum "api/package.json" }}
          paths:
            - api/node_modules

workflows:
  version: 2
  deploy:
    jobs:
      - pre-build:
          <<: *workflow
      - api:
          <<: *workflow
          requires:
            - pre-build
      - react:
          <<: *workflow
          requires:
            - pre-build
      - e2e:
          <<: *workflow
          requires:
            - pre-build


